# Visualize and pre-process datatset
## Imports

In [43]:
import numpy as np
from pathlib import Path
import gzip
import tqdm
from typing import Tuple

## Extract the gz archive.
Data path

In [44]:
data_path: Path = Path("../../../dataset/2/models_by_code/models/DYKE_FOLD_DYKE")
files_to_extract = data_path.glob("*")
nbr_files_to_extract = len([_ for _ in data_path.glob("*")])
print(f"{nbr_files_to_extract} files in {data_path}.")

2022 files in ..\..\..\dataset\2\models_by_code\models\DYKE_FOLD_DYKE.


Extract every archive of the folder

In [48]:
def remove_all_suffixes(path: Path) -> Path:
    while path.suffix:
        path = path.with_suffix("")
    return path

def save_array(npz_file_counter: int,
               combined_array: np.ndarray
               ) -> Tuple[int, np.ndarray]:
    np.savez_compressed(data_path / f"{npz_file_counter}.npz", combined_array)
    print(f"Saved {npz_file_counter}.npz.")
    npz_file_counter += 1
    # Return a new empty buffer with the same dimensions.
    return npz_file_counter, np.empty((500, 200, 200), dtype=np.float64)

indexes_list = [0, 100, 199]

counter: int = 0
npz_file_counter: int = 0

combined_array: np.ndarray = np.empty((500, 200, 200), dtype=np.float64)

for file in tqdm.tqdm(files_to_extract, desc="Extraction", unit="file", total=nbr_files_to_extract):
    with gzip.open(file, 'rb') as gz_file:
        g12_array = np.loadtxt(gz_file, dtype=np.int8)
    break
g12_array = g12_array.reshape((200, 200, 200))
print(g12_array.itemsize * g12_array.size)
print(g12_array[:, :, 0])
print(g12_array[:, 50, :])
"""
    # Reformat the array
    g12_array = g12_array.reshape((200, 200, 200))  # We now have (z, x, y) array.
    for array_sample, index in enumerate(indexes_list):
        if counter + array_sample == 500:
            npz_file_counter, combined_array = save_array(npz_file_counter, combined_array)
            counter = 0
        combined_array[counter + array_sample] = g12_array[:, :, index]
    counter += len(indexes_list)
    for array_sample, index in enumerate(indexes_list):
        if counter + array_sample == 500:
            npz_file_counter, combined_array = save_array(npz_file_counter, combined_array)
            counter = 0
        combined_array[counter + array_sample] = g12_array[:, index, :]
    counter += len(indexes_list)
    file.unlink()
_ = save_array(npz_file_counter, combined_array)"""

Extraction:   0%|          | 0/2022 [00:00<?, ?file/s]

8000000
[[5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 ...
 [7 7 7 ... 5 5 5]
 [7 7 7 ... 5 5 5]
 [7 7 7 ... 5 5 5]]
[[7 7 7 ... 1 1 1]
 [7 7 7 ... 1 1 1]
 [7 7 7 ... 1 1 1]
 ...
 [5 5 5 ... 3 3 3]
 [5 5 5 ... 3 3 3]
 [5 5 5 ... 3 3 3]]


'\n    # Reformat the array\n    g12_array = g12_array.reshape((200, 200, 200))  # We now have (z, x, y) array.\n    for array_sample, index in enumerate(indexes_list):\n        if counter + array_sample == 500:\n            npz_file_counter, combined_array = save_array(npz_file_counter, combined_array)\n            counter = 0\n        combined_array[counter + array_sample] = g12_array[:, :, index]\n    counter += len(indexes_list)\n    for array_sample, index in enumerate(indexes_list):\n        if counter + array_sample == 500:\n            npz_file_counter, combined_array = save_array(npz_file_counter, combined_array)\n            counter = 0\n        combined_array[counter + array_sample] = g12_array[:, index, :]\n    counter += len(indexes_list)\n    file.unlink()\n_ = save_array(npz_file_counter, combined_array)'